#!/usr/bin/env node

import { copyFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRuntimeBuilder } from "./runtime-builder.mjs";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** Runtime assets resolved by file URL at runtime; esbuild bundles only the TS graph. */
const runtimeAssets = ["src/srt-launcher.mjs"];

const builder = createRuntimeBuilder({
  packageRoot,
  temporaryPrefix: ".pi-plan-mode",
  banner: [
    "// @generated by scripts/build-runtime.mjs; do not edit.",
    "// @ts-nocheck -- the generated entry uses a .ts extension for Pi's Jiti loader.",
  ].join("\n"),
  forbiddenEagerInputs: [
    "src/interactive-ui.ts",
    "src/active-implementation-menu.ts",
    "src/plan-export-screen.ts",
    "src/plan-action-menus.ts",
    "src/plan-launch-menu.ts",
    "src/saved-plan-menu.ts",
    "src/settings-menu.ts",
  ],
  forbiddenEagerExternals: ["@narumitw/pi-tui-kit"],
});

export const { validateEagerGraph, validateGeneratedFiles, publishRuntime } = builder;

const baseBuildRuntime = builder.buildRuntime;

export async function buildRuntime(options = {}) {
  const metadata = await baseBuildRuntime(options);
  // The generated entry resolves srt-launcher.mjs relative to its own URL, so the runtime assets
  // must sit next to the published output or the sandbox probe cannot spawn the launcher.
  const outputDirectory = resolve(options.outputDirectory ?? join(packageRoot, "dist"));
  for (const asset of runtimeAssets) {
    await copyFile(join(packageRoot, asset), join(outputDirectory, basename(asset)));
  }
  return metadata;
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (invokedPath === import.meta.url) await buildRuntime();
